tasks:
    - name: Start web server
      before: cd ../public
      init: python -m http.server 5000
image:
  file: .gitpod.Dockerfile


ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - eg2.vscode-npm-script